ignore_colors = [
	[0, 0, 0, 0],
	# [0, 0, 0, 255], # filter all black
]

version = 11

[[structure]]
name = "hololive_text"
file = "images/hololive_text.png"
startx = 240
starty = 737

[[structure]]
name = "asacoco"
file = "images/asacoco.png"
startx = 257
starty = 753

[[structure]]
name = "yagoo"
file = "images/yagoo.png"
startx = 1332
starty = 902