ignore_colors = [
	[0, 0, 0, 0],
	# [0, 0, 0, 255], # filter all black
]

version = 11

[[structure]]
name = "hololive_text"
file = "images/hololive_text.png"
startx = 240
starty = 737

[[structure]]
name = "vshoujo"
file = "images/vshoujo.png"
startx = 165
starty = 749

[[structure]]
name = "asacoco"
file = "images/asacoco.png"
startx = 257
starty = 753

[[structure]]
name = "yagoo"
file = "images/yagoo.png"
startx = 1332
starty = 900

[[structure]]
name = "flare"
file = "images/Flare.png"
startx = 1365
starty = 869

[[structure]]
name = "fubuhappy"
file = "images/fubuhappy.png"
startx = 1333
starty = 870

